name: Build and Deploy Fullstack App

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js for building the client
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install and build client project
      - name: Build Client Project
        run: |
          cd client
          npm install
          npm run build  # Adjust if using Angular or other frameworks

      # Set up backend service (e.g., Node.js)
      - name: Set Up Service
        run: |
          cd service
          npm install
          # Add steps to start/test your backend server

      # Deploy Client to GitHub Pages
      - name: Deploy Client to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist  # Adjust the path for your build output
