name: Build and Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build the Angular client
      - name: Build Angular App
        run: |
          cd client
          npm ci
          npm run build -- --configuration production

      # Publish the ASP.NET Core server
      - name: Build and Publish Server
        run: |
          cd server
          dotnet restore
          dotnet publish -c Release -o publish

      # Deploy both client and server
      - name: Deploy Application
        run: |
          # Example: Deploy to Azure, AWS, or a self-hosted environment
          # Replace with your deployment steps
          echo "Deploying application..."
